### ISSUE TITLE
Permissions required

### ISSUE THREAD

**Issue by enduring78** [eduardogsilva/routerfleet#10]
Hi! I set this up today after having trouble comparing backup versions. 

Looks nice, but it requires a admin user. Can this be changed? Read permissions should be enough, since I restore the file myself right?

**Comment by eduardogsilva** [comment]
Hello @enduring78 for the user being able to view/compare/download and take instant backups, the required user level is Backup operator (just one level higher than view only).

This user level cannot change any other configuration.

**Comment by eduardogsilva** [comment]
Ah ok, now I understand. 

If the routeros requires admin privilege, there's not much that I can do here.

Routerfleet needs to connect using ssh and execute the scp for fetching the files.
The user that you are creating, need to be able to execute those steps on the router.

I will be closing this issue, since it's not an issue on routerfleet side.
