### ISSUE TITLE
Won't update

### ISSUE THREAD

**Issue by jfreak53** [eduardogsilva/routerfleet#27]
Tried multiple times, it still won't upgrade past 0.7006. I run below commands from inside the routerfleet dir:

```
docker-compose down
rm -f docker-compose.yml
wget -O docker-compose.yml https://raw.githubusercontent.com/eduardogsilva/routerfleet/main/docker-compose.yml
docker-compose up -d
```

Comes back up, I go back into the page, it asks me to login, but same version remains. I'm running Ubu 22.04. docker-compose version 1.29.2, and Docker version 24.0.5, all from ubu repos.

**Comment by eduardogsilva** [comment]
I've noticed this on my updates here. I don't understand, but looks like the local docker compose is using cached images without checking for updates. If someone have any insight on this, it would be great. 

As a workaround, you can try to do the following:

```
docker compose down
docker system prune -a
wget...
docker-compose up -d

```
Observations: 
- No need to rm the docker compose file, the wget already replaces it.
- system prune will remove all your images not related to any running container, so the update will be longer.
- Just as a tip (not related to the reported issue), instead of using "docker-compose" use "docker compose" it's the updated version.

If you discover why we are having cache issues, please let me know.

I hope this steps fix for you.

**Comment by eduardogsilva** [comment]
please try docker compose pull   instead of system prune

**Comment by jfreak53** [comment]
Prune worked. I was already in the process when you sent the second response, I'll try `pull` next time.

FYI, its updated, but still shows update pending bar at the bottom:
https://cdn.microtronix-tech.com/imgs/Screenshot_at_2024-04-15_10-44-43.jpg

> Just as a tip (not related to the reported issue), instead of using "docker-compose" use "docker compose" it's the updated version.

Doesn't work on this version of docker without the dash, I tried, just says it doesn't know what compose command is. So I run with the dash, it works.

**Comment by eduardogsilva** [comment]
Don't mind the update pending in the bottom, it will be gone in less than 1hr. I will fix this soon. 

Later today, you should see another update notification. There's a bunch of quality of life updates coming! ;)

**Comment by eduardogsilva** [comment]
I just confirmed, ```docker compose pull``` should update the local images.
I've updated the instructions at README.md

Thanks for pointing it out.
Cheers!
