### ISSUE TITLE
Device discovery

### ISSUE THREAD

**Issue by EtherAddict** [eduardogsilva/routerfleet#30]
When deploying in larger networks being able to add an IP range to discover devices would be awesome instead of adding every device independently.

Love the project!

**Comment by eduardogsilva** [comment]
Hi @EtherAddict 

Thank you for the device discovery feature suggestion. It’s an interesting idea that could add significant functionality to RouterFleet. I’ve outlined a few potential implementation options and have some concerns regarding each:

### Proposed Options for Device Discovery
1. **Simple Discovery with Manual Addition**
   - Discover devices with an open SSH port.
   - Display each discovered device with an option to manually add it to RouterFleet by clicking an "add" button. This would pre-fill the device's address in the current add/edit router screen.

2. **Automated Discovery with Credentials**
   - Allow users to initiate a discovery scan by specifying router type, login credentials (username + password or key), and an IP address range.
   - Automatically add discovered hosts that match the provided OS and credentials.

3. **Automated Discovery without Specifying Router Type**
   - Similar to Option 2, but without specifying the router type.
   - After successful login, RouterFleet would attempt to determine the router type by executing OS-specific commands.

### Concerns
- **Relevance of Option 1**: It might not be very useful as it only slightly automates the process but still requires significant manual intervention.
- **Security Concerns with Automated Addition (Options 2 and 3)**:
  - Encourages poor security practices among network administrators, such as reusing the same credentials across multiple devices.
  - Potentially exposes sensitive credentials to honeypots or malicious entities on the network.
  - Maintaining the feature could become complex and risky as the variety of supported router types expands.

### Alternative Suggestion
- **CSV Import Tool**: Instead of automated discovery, an import tool where administrators can upload a CSV file with details of multiple routers. This method provides bulk addition capabilities while allowing for better control over the security of credentials.

I'd love to hear your thoughts on these options and any other ideas you might have. 

Cheers!

**Comment by jakes0ns** [comment]
I Think CSV import is a great idea. Other big players use this feature, it would be good to also be able to import names for the routers other then simply just pulling the router ID

**Comment by eduardogsilva** [comment]
@jakes0ns I plan to fetch some router information, including hardware information, cpu, ram, id, os version and some extra info. This information should be updated automatically every day or so.

**Comment by eduardogsilva** [comment]
Just as an update, I've implemented the CSV import tool.
https://github.com/eduardogsilva/routerfleet/discussions/35
Cheers!
